name: "bluebell"
mode: "dev"
port: 8081
version: "v0.0.1"
start_time: "2023-10-31"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "info"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "47.102.119.88"
  port: 3306
  user: "root"
  password: "dhxdl666"
  dbname: "sql_demo"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "47.102.119.88"
  port: 16379
  password: "dhxdl666"
  db: 0
  pool_size: 100
  min_idle_conns: 50

